# Generated by Django 6.0.7 on 2026-08-16 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30, unique=True, verbose_name='Numenro da Matricula')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Matriculado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('status', models.CharField(choices=[('ATIVA', 'Ativo'), ('CONCLUIDA', 'Concluída'), ('CANCELEDA', 'Cancelada'), ('TRANCADA', 'Trancada')], default='ATIVA', max_length=12, verbose_name='Status')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='academics.group', verbose_name='Turma')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='accounts.student', verbose_name='Aluno')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('student', 'group'), name='unique_student_group')],
            },
        ),
    ]
