# Generated by Django 6.0.7 on 2026-08-17 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrollment',
            options={'verbose_name': 'Matricula'},
        ),
    ]
