# Generated by Django 6.0.7 on 2026-08-18 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0002_alter_enrollment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='number',
            field=models.CharField(auto_created=True, max_length=30, unique=True, verbose_name='Numenro da Matricula'),
        ),
    ]
