# Generated by Django 6.0.7 on 2026-08-18 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0003_alter_enrollment_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='number',
            field=models.CharField(max_length=30, unique=True, verbose_name='Numenro da Matricula'),
        ),
    ]
