# Generated by Django 6.0.7 on 2026-08-18 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0004_alter_enrollment_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='number',
        ),
    ]
