"""
Django settings for schoolApp project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from django.templatetags.static import static
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-&#sgfph#3edrif@8ab9q2t_ft0beu)myd%0dphjcf3xhf&(oq2'

# SECURITY WARNING: don't run with debug turned on in production!

#DEVELOPMET  ENVIROMENT
DEBUG = True
ALLOWED_HOSTS = ['127.0.0.1', 'localhost']

#PRODUCTION ENVIROMENT
#DEBUG = False
#ALLOWED_HOSTS = ['127.0.0.1', 'localhost']


# Application definition

INSTALLED_APPS = [
    #'jazzmin',
    "unfold",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    #MY APPS
    'accounts',
    'academics',
    'enrollments',
    'grades',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'schoolApp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR/'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'schoolApp.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'pt-pt'

TIME_ZONE = 'Africa/Luanda'

USE_I18N = True

USE_TZ = True

LANGUAGES = [ 
    ("pt", "Portuguese"),
    ("en", "English"),
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR/'static',
]


LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'login'


UNFOLD = {
    # Identidade do sistema
    "SITE_TITLE": "SchoolApp | Gestão Académica",
    "SITE_HEADER": "BSOFT SCHOOL",
    "SITE_SUBHEADER": "Sistema de Gestão Académica",
    "SITE_VERSION": "1.0.0",
    "SITE_URL": "/",

    # Ícone e símbolo do sistema
    "SITE_SYMBOL": "school",

    # Opções da interface
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": False,
    "SHOW_BACK_BUTTON": True,
    "SHOW_UI_WARNINGS": False,

    # Tema
    "THEME": "light",

    # Estilos personalizados
    "STYLES": [
        lambda request: static("css/style.css"),
    ],

    # Scripts personalizados
    "SCRIPTS": [
        lambda request: static("js/script.js"),
    ],

    # Arredondamento dos elementos
    "BORDER_RADIUS": "8px",

    # Cores do sistema
    "COLORS": {
        "base": {
            "50": "oklch(98% .003 247)",
            "100": "oklch(96% .005 247)",
            "200": "oklch(92% .008 247)",
            "300": "oklch(86% .012 247)",
            "400": "oklch(70% .018 247)",
            "500": "oklch(55% .025 247)",
            "600": "oklch(43% .03 247)",
            "700": "oklch(34% .035 247)",
            "800": "oklch(25% .035 247)",
            "900": "oklch(18% .03 247)",
            "950": "oklch(12% .025 247)",
        },

        "primary": {
            "50": "oklch(97% .015 245)",
            "100": "oklch(93% .03 245)",
            "200": "oklch(87% .06 245)",
            "300": "oklch(78% .10 245)",
            "400": "oklch(68% .15 245)",
            "500": "oklch(58% .19 245)",
            "600": "oklch(50% .20 245)",
            "700": "oklch(42% .18 245)",
            "800": "oklch(34% .15 245)",
            "900": "oklch(27% .12 245)",
            "950": "oklch(20% .09 245)",
        },

        "font": {
            "subtle-light": "var(--color-base-500)",
            "subtle-dark": "var(--color-base-400)",
            "default-light": "var(--color-base-700)",
            "default-dark": "var(--color-base-300)",
            "important-light": "var(--color-base-900)",
            "important-dark": "var(--color-base-100)",
        },
    },

    # Menu lateral
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False,

        "navigation": [
            {
                "title": _("Principal"),
                "separator": True,
                "collapsible": False,
                "items": [
                    {
                        "title": _("Dashboard"),
                        "icon": "dashboard",
                        "link": reverse_lazy("admin:index"),
                    },
                ],
            },

            {
                "title": _("Utilizadores"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Utilizadores do sistema"),
                        "icon": "people",
                        "link": reverse_lazy("admin:auth_user_changelist"),
                    },
                    {
                        "title": _("Grupos e permissões"),
                        "icon": "admin_panel_settings",
                        "link": reverse_lazy("admin:auth_group_changelist"),
                    },
                ],
            },

            {
                "title": _("Gestão Académica"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Alunos"),
                        "icon": "school",
                        "link": reverse_lazy("admin:accounts_student_changelist"),
                    },
                    {
                        "title": _("Professores"),
                        "icon": "person",
                        "link": reverse_lazy("admin:accounts_teacher_changelist"),
                    },
                    {
                        "title": _("Cursos"),
                        "icon": "menu_book",
                        "link": reverse_lazy("admin:academics_course_changelist"),
                    },
                    {
                        "title": _("Disciplinas"),
                        "icon": "library_books",
                        "link": reverse_lazy("admin:academics_subject_changelist"),
                    },
                    {
                        "title": _("Anos letivos"),
                        "icon": "calendar_month",
                        "link": reverse_lazy("admin:academics_academicyear_changelist"),
                    },
                    {
                        "title": _("Turmas"),
                        "icon": "groups",
                        "link": reverse_lazy("admin:academics_group_changelist"),
                    },
                    {
                        "title": _("Atribuições de professores"),
                        "icon": "assignment_ind",
                        "link": reverse_lazy(
                            "admin:academics_teacherassignment_changelist"
                        ),
                    },
                ],
            },

            {
                "title": _("Matrículas"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Matrículas dos alunos"),
                        "icon": "how_to_reg",
                        "link": reverse_lazy(
                            "admin:enrollments_enrollment_changelist"
                        ),
                    },
                ],
            },

            {
                "title": _("Avaliações e Notas"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Tipos de avaliação"),
                        "icon": "category",
                        "link": reverse_lazy(
                            "admin:grades_evaluation_changelist"
                        ),
                    },
                    {
                        "title": _("Avaliações académicas"),
                        "icon": "assignment",
                        "link": reverse_lazy(
                            "admin:grades_academicevaluation_changelist"
                        ),
                    },
                    {
                        "title": _("Notas"),
                        "icon": "grading",
                        "link": reverse_lazy(
                            "admin:grades_grade_changelist"
                        ),
                    },

                      {
                        "title": _("Pautas"),
                        "icon": "grading",
                        "link": reverse_lazy(
                            "admin:grades_gradebook_changelist"
                        ),
                    },
                ],
            },
        ],
    },

    "SHOW_LANGUAGE": True,
}