"""
Django settings for schoolApp project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from django.templatetags.static import static
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-&#sgfph#3edrif@8ab9q2t_ft0beu)myd%0dphjcf3xhf&(oq2'

# SECURITY WARNING: don't run with debug turned on in production!

#DEVELOPMET  ENVIROMENT
DEBUG = True
ALLOWED_HOSTS = ['127.0.0.1', 'localhost']

#PRODUCTION ENVIROMENT
#DEBUG = False
#ALLOWED_HOSTS = ['127.0.0.1', 'localhost']


# Application definition

INSTALLED_APPS = [
      
    'unfold',
    #'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    #MY APPS
    'accounts',
    'academics',
    'enrollments',
    'grades',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'schoolApp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR/'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'schoolApp.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

TIME_ZONE = 'Africa/Luanda'
USE_I18N = True
USE_TZ = True

LANGUAGES = [
    ("pt", "Portuguese"),
    ("en", "English"),
    ("fr", "French"),
    ("es", "Spanish"),
    ("de", "German"),
    ("it", "Italian"),
    ("zh-hans", "Chinese"),
    ("ru", "Russian"),
    ("ar", "Arabic"), 
]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR/'static',
]


LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'login'


#ESTILIZAÇÃO DO ADMINISTRADOR COM UNFOLD
UNFOLD = {
    # Identidade do sistema
    "SITE_TITLE": " BSOFT SCHOOL | Gestão Académica",
    "SITE_HEADER": "BSOFT SCHOOL",
    "SITE_SUBHEADER": "SIGAcadémica",
    "SITE_VERSION": "1.0.0",
    "SITE_URL": "/",

    # Ícone e símbolo do sistema
    "SITE_SYMBOL": "school",
     "DASHBOARD_CALLBACK": "schoolApp.dashboard.dashboard_callback",

    # Opções da interface
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": False,
    "SHOW_BACK_BUTTON": True,
    "SHOW_UI_WARNINGS": False,

    # CORREÇÃO: removido "THEME": "light". Ao forçar um tema único, o
    # seletor de dark mode desaparece da interface. Deixando por
    # definir, o Unfold mostra o alternador de tema (claro/escuro) —
    # é o comportamento "moderno" esperado num admin atual, e cada
    # utilizador escolhe o que prefere sem afetar os outros.

    # Estilos e scripts personalizados
    "STYLES": [
        lambda request: static("css/style.css"),
    ],
    "SCRIPTS": [
        lambda request: static("js/script.js"),
    ],

    # CORREÇÃO: 8px -> 10px. Um raio ligeiramente maior dá um ar mais
    # suave/atual aos cartões e botões (efeito usado por interfaces
    # modernas como Linear, Notion), sem exagerar a ponto de parecer
    # "bolha".
    "BORDER_RADIUS": "10px",

    # Cores do sistema — paleta azul limpa e profissional, adequada a
    # um contexto académico/institucional (transmite confiança e
    # neutralidade, ao contrário de tons mais "vivos" como roxo/verde).
    "COLORS": {
        # Base neutra (cinza-azulado) — usada em texto, bordas, fundos.
        # Mantida igual ao exemplo oficial do Unfold: é a escala que
        # o próprio tema usa para garantir bom contraste em claro/escuro.
        "base": {
            "50": "oklch(98.5% .002 247.839)",
            "100": "oklch(96.7% .003 264.542)",
            "200": "oklch(92.8% .006 264.531)",
            "300": "oklch(87.2% .01 258.338)",
            "400": "oklch(70.7% .022 261.325)",
            "500": "oklch(55.1% .027 264.364)",
            "600": "oklch(44.6% .03 256.802)",
            "700": "oklch(37.3% .034 259.733)",
            "800": "oklch(27.8% .033 256.848)",
            "900": "oklch(21% .034 264.665)",
            "950": "oklch(13% .028 261.692)",
        },

        # Cor primária — azul limpo (em vez do tom mais frio/acinzentado
        # que tinhas), com progressão suave do claro ao escuro.
        "primary": {
            "50": "oklch(97.7% .014 254)",
            "100": "oklch(94.6% .033 254)",
            "200": "oklch(90.2% .063 254)",
            "300": "oklch(82.7% .119 254)",
            "400": "oklch(71.4% .18 254)",
            "500": "oklch(62.7% .22 254)",
            "600": "oklch(55.8% .24 254)",
            "700": "oklch(49.6% .22 254)",
            "800": "oklch(43.8% .19 254)",
            "900": "oklch(38.1% .15 254)",
            "950": "oklch(29.1% .13 254)",
        },

        # CORREÇÃO: mapeamento de texto alinhado com a recomendação
        # oficial do Unfold (usavas 700/400 no "default", a doc
        # recomenda 600/300 — dá texto ligeiramente mais claro/legível
        # em ambos os temas, sem perder contraste com o fundo).
        "font": {
            "subtle-light": "var(--color-base-500)",
            "subtle-dark": "var(--color-base-400)",
            "default-light": "var(--color-base-600)",
            "default-dark": "var(--color-base-300)",
            "important-light": "var(--color-base-900)",
            "important-dark": "var(--color-base-100)",
        },
    },

    # Menu lateral
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False,

        "navigation": [
            {
                "title": _("Principal"),
                "separator": True,
                "collapsible": False,
                "items": [
                    {
                        "title": _("Dashboard"),
                        "icon": "dashboard",
                        "link": reverse_lazy("admin:index"),
                    },
                ],
            },

            {
                "title": _("Utilizadores"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Utilizadores do sistema"),
                        "icon": "people",
                        "link": reverse_lazy("admin:auth_user_changelist"),
                    },
                    {
                        "title": _("Grupos e permissões"),
                        "icon": "admin_panel_settings",
                        "link": reverse_lazy("admin:auth_group_changelist"),
                    },
                ],
            },

            {
                "title": _("Gestão Académica"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Alunos"),
                        "icon": "school",
                        "link": reverse_lazy("admin:accounts_student_changelist"),
                    },
                    {
                        "title": _("Professores"),
                        "icon": "person",
                        "link": reverse_lazy("admin:accounts_teacher_changelist"),
                    },
                    {
                        "title": _("Cursos"),
                        "icon": "menu_book",
                        "link": reverse_lazy("admin:academics_course_changelist"),
                    },
                    {
                        "title": _("Disciplinas"),
                        "icon": "library_books",
                        "link": reverse_lazy("admin:academics_subject_changelist"),
                    },
                    {
                        "title": _("Anos letivos"),
                        "icon": "calendar_month",
                        "link": reverse_lazy("admin:academics_academicyear_changelist"),
                    },
                    {
                        "title": _("Turmas"),
                        "icon": "groups",
                        "link": reverse_lazy("admin:academics_group_changelist"),
                    },
                    {
                        "title": _("Atribuições de professores"),
                        "icon": "assignment_ind",
                        "link": reverse_lazy(
                            "admin:academics_teacherassignment_changelist"
                        ),
                    },
                ],
            },

            {
                "title": _("Matrículas"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Matrículas dos alunos"),
                        "icon": "how_to_reg",
                        "link": reverse_lazy(
                            "admin:enrollments_enrollment_changelist"
                        ),
                    },
                ],
            },

            {
                "title": _("Avaliações e Notas"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Tipos de avaliação"),
                        "icon": "category",
                        "link": reverse_lazy(
                            "admin:grades_evaluation_changelist"
                        ),
                    },
                    {
                        "title": _("Avaliações académicas"),
                        "icon": "assignment",
                        "link": reverse_lazy(
                            "admin:grades_academicevaluation_changelist"
                        ),
                    },
                    {
                        "title": _("Notas"),
                        "icon": "grading",
                        "link": reverse_lazy(
                            "admin:grades_grade_changelist"
                        ),
                    },
                    {
                        # CORREÇÃO: ícone repetido ("grading", igual ao
                        # de "Notas" acima) — trocado por "fact_check",
                        # mais distinto visualmente na sidebar.
                        "title": _("Pautas"),
                        "icon": "fact_check",
                        "link": reverse_lazy(
                            "admin:grades_gradebook_changelist"
                        ),
                    },
                ],
            },
        ],
    },

    "SHOW_LANGUAGES": True,
}