"""
Django settings for schoolApp project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url
from django.templatetags.static import static
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# =========================================================
# 1. AMBIENTE (desenvolvimento vs produção)
#    Localmente: DEBUG=True por defeito.
#    No Render: a variável RENDER=true é definida automaticamente,
#    por isso o DEBUG fica False (a menos que definas DEBUG=True).
# =========================================================
ON_RENDER = bool(os.environ.get("RENDER"))
DEBUG = os.environ.get("DEBUG", "False" if ON_RENDER else "True") == "True"

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "SECRET_KEY",
    "django-insecure-chave-apenas-para-desenvolvimento-local",
)

ALLOWED_HOSTS = ["127.0.0.1", "localhost"]
RENDER_EXTERNAL_HOSTNAME = os.environ.get("RENDER_EXTERNAL_HOSTNAME")
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)

CSRF_TRUSTED_ORIGINS = ["https://*.onrender.com"]


# Application definition

INSTALLED_APPS = [
    'unfold',
    # 'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # MY APPS
    'accounts',
    'academics',
    'enrollments',
    'grades',
    'axes',  # deve vir perto do fim (segurança, brute force)
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # logo a seguir ao SecurityMiddleware
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'axes.middleware.AxesMiddleware',  # sempre o último
]

ROOT_URLCONF = 'schoolApp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'schoolApp.wsgi.application'


# =========================================================
# 2. BASE DE DADOS
#    Localmente usa SQLite. No Render usa a DATABASE_URL (Neon).
#    (Antes havia dois blocos DATABASES e o segundo, SQLite,
#    sobrepunha-se ao primeiro, por isso o Neon nunca seria usado.)
# =========================================================
DATABASES = {
    "default": dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# =========================================================
# 3. AUTHENTICATION_BACKENDS — AxesStandaloneBackend TEM de
#    ser o primeiro, senão o axes não intercepta o login
# =========================================================
AUTHENTICATION_BACKENDS = [
    "axes.backends.AxesStandaloneBackend",  # tem de ser o primeiro
    "django.contrib.auth.backends.ModelBackend",
]


# =========================================================
# 4. CONFIGURAÇÃO DO DJANGO-AXES (bloqueio por tentativas falhadas)
# =========================================================
AXES_FAILURE_LIMIT = 3                  # bloqueia ao fim de 3 tentativas erradas
AXES_COOLOFF_TIME = 0.25                # desbloqueia ao fim de 15 minutos (em horas)
AXES_LOCKOUT_PARAMETERS = ["username"]  # bloqueia só por username (atrás do proxy do Render o IP seria sempre o mesmo)
AXES_RESET_ON_SUCCESS = True            # um login correto reinicia o contador


# =========================================================
# 5. COOKIES E SESSÃO
# =========================================================
SESSION_COOKIE_HTTPONLY = True      # JavaScript não consegue ler o cookie de sessão
CSRF_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_SAMESITE = "Lax"
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_COOKIE_AGE = 60 * 60 * 1    # sessão expira ao fim de 1h


# =========================================================
# 6. CABEÇALHOS HTTP DE SEGURANÇA
# =========================================================
X_FRAME_OPTIONS = "DENY"                # impede o site de ser carregado num <iframe>
SECURE_CONTENT_TYPE_NOSNIFF = True      # impede o browser de "adivinhar" tipos de ficheiro
# (SECURE_BROWSER_XSS_FILTER foi removido: já não existe no Django moderno)

# Em produção (Render, com HTTPS), ativa automaticamente:
if not DEBUG:
    # O Render termina o HTTPS no proxy; isto diz ao Django que o pedido original era seguro
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 3600  # sobe para 31536000 quando estiveres seguro de que o HTTPS está estável
    SECURE_HSTS_INCLUDE_SUBDOMAINS = False
    SECURE_HSTS_PRELOAD = False


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'pt'
TIME_ZONE = 'Africa/Luanda'
USE_I18N = True
USE_TZ = True

LANGUAGES = [
    ("pt", "Portuguese"),
    ("en", "English"),
    ("fr", "French"),
    ("es", "Spanish"),
    ("de", "German"),
    ("it", "Italian"),
    ("zh-hans", "Chinese"),
    ("ru", "Russian"),
    ("ar", "Arabic"),
    ("pt-br", "Brazilian Portuguese"),
]


# =========================================================
# 7. FICHEIROS ESTÁTICOS (WhiteNoise)
# =========================================================
STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "staticfiles"

# Se tens uma pasta "static" na raiz do projeto (com css/style.css e js/script.js),
# ela tem de ser registada aqui, senão o collectstatic não a encontra.
if (BASE_DIR / "static").exists():
    STATICFILES_DIRS = [BASE_DIR / "static"]

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}
WHITENOISE_MANIFEST_STRICT = False


LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'login'


# ESTILIZAÇÃO DO ADMINISTRADOR COM UNFOLD
UNFOLD = {
    # Identidade do sistema
    "SITE_TITLE": " BSOFT SCHOOL | Gestão Académica",
    "SITE_HEADER": "BSOFT SCHOOL",
    "SITE_SUBHEADER": "SIGAcadémica",
    "SITE_VERSION": "1.0.0",
    "SITE_URL": "/",

    # Ícone e símbolo do sistema
    "SITE_SYMBOL": "school",
    "DASHBOARD_CALLBACK": "schoolApp.dashboard.dashboard_callback",

    # Opções da interface
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": False,
    "SHOW_BACK_BUTTON": True,
    "SHOW_UI_WARNINGS": False,

    # Sem "THEME" forçado: o Unfold mostra o alternador claro/escuro.

    # Estilos e scripts personalizados
    "STYLES": [
        lambda request: static("css/style.css"),
    ],
    "SCRIPTS": [
        lambda request: static("js/script.js"),
    ],

    "BORDER_RADIUS": "10px",

    # Cores do sistema — paleta azul limpa e profissional
    "COLORS": {
        "base": {
            "50": "oklch(98.5% .002 247.839)",
            "100": "oklch(96.7% .003 264.542)",
            "200": "oklch(92.8% .006 264.531)",
            "300": "oklch(87.2% .01 258.338)",
            "400": "oklch(70.7% .022 261.325)",
            "500": "oklch(55.1% .027 264.364)",
            "600": "oklch(44.6% .03 256.802)",
            "700": "oklch(37.3% .034 259.733)",
            "800": "oklch(27.8% .033 256.848)",
            "900": "oklch(21% .034 264.665)",
            "950": "oklch(13% .028 261.692)",
        },
        "primary": {
            "50": "oklch(97.7% .014 254)",
            "100": "oklch(94.6% .033 254)",
            "200": "oklch(90.2% .063 254)",
            "300": "oklch(82.7% .119 254)",
            "400": "oklch(71.4% .18 254)",
            "500": "oklch(62.7% .22 254)",
            "600": "oklch(55.8% .24 254)",
            "700": "oklch(49.6% .22 254)",
            "800": "oklch(43.8% .19 254)",
            "900": "oklch(38.1% .15 254)",
            "950": "oklch(29.1% .13 254)",
        },
        "font": {
            "subtle-light": "var(--color-base-500)",
            "subtle-dark": "var(--color-base-400)",
            "default-light": "var(--color-base-600)",
            "default-dark": "var(--color-base-300)",
            "important-light": "var(--color-base-900)",
            "important-dark": "var(--color-base-100)",
        },
    },

    # Menu lateral
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False,

        "navigation": [
            {
                "title": _("Principal"),
                "separator": True,
                "collapsible": False,
                "items": [
                    {
                        "title": _("Dashboard"),
                        "icon": "dashboard",
                        "link": reverse_lazy("admin:index"),
                    },
                ],
            },

            {
                "title": _("Utilizadores"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Utilizadores do sistema"),
                        "icon": "people",
                        "link": reverse_lazy("admin:auth_user_changelist"),
                    },
                    {
                        "title": _("Grupos e permissões"),
                        "icon": "admin_panel_settings",
                        "link": reverse_lazy("admin:auth_group_changelist"),
                    },
                ],
            },

            {
                "title": _("Gestão Académica"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Alunos"),
                        "icon": "school",
                        "link": reverse_lazy("admin:accounts_student_changelist"),
                    },
                    {
                        "title": _("Professores"),
                        "icon": "person",
                        "link": reverse_lazy("admin:accounts_teacher_changelist"),
                    },
                    {
                        "title": _("Cursos"),
                        "icon": "menu_book",
                        "link": reverse_lazy("admin:academics_course_changelist"),
                    },
                    {
                        "title": _("Disciplinas"),
                        "icon": "library_books",
                        "link": reverse_lazy("admin:academics_subject_changelist"),
                    },
                    {
                        "title": _("Anos letivos"),
                        "icon": "calendar_month",
                        "link": reverse_lazy("admin:academics_academicyear_changelist"),
                    },
                    {
                        "title": _("Turmas"),
                        "icon": "groups",
                        "link": reverse_lazy("admin:academics_group_changelist"),
                    },
                    {
                        "title": _("Atribuições de professores"),
                        "icon": "assignment_ind",
                        "link": reverse_lazy(
                            "admin:academics_teacherassignment_changelist"
                        ),
                    },
                ],
            },

            {
                "title": _("Matrículas"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Matrículas dos alunos"),
                        "icon": "how_to_reg",
                        "link": reverse_lazy(
                            "admin:enrollments_enrollment_changelist"
                        ),
                    },
                ],
            },

            {
                "title": _("Avaliações e Notas"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Tipos de avaliação"),
                        "icon": "category",
                        "link": reverse_lazy(
                            "admin:grades_evaluation_changelist"
                        ),
                    },
                    {
                        "title": _("Avaliações académicas"),
                        "icon": "assignment",
                        "link": reverse_lazy(
                            "admin:grades_academicevaluation_changelist"
                        ),
                    },
                    {
                        "title": _("Notas"),
                        "icon": "grading",
                        "link": reverse_lazy(
                            "admin:grades_grade_changelist"
                        ),
                    },
                    {
                        "title": _("Pautas"),
                        "icon": "fact_check",
                        "link": reverse_lazy(
                            "admin:grades_gradebook_changelist"
                        ),
                    },
                ],
            },
        ],
    },

    "SHOW_LANGUAGES": True,
}