# Generated by Django 6.0.7 on 2026-08-16 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('enrollments', '0001_initial'),
    ]

    

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Avalição')),
                ('type', models.CharField(choices=[('TESTE', 'Teste'), ('TRABALHO', 'Trabalho'), ('PROVA', 'Prova'), ('EXAME', 'Exame'), ('RECURSO', 'Reucrso')], max_length=20, verbose_name='Tipo de Avalição')),
                ('gradeWeight', models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='Peso da Nota')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Data da realização')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='avaluations', to='academics.subject', verbose_name='Disciplina')),
            ],
        ),
        migrations.CreateModel(
            name='GradeBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted', models.BooleanField(default=False, verbose_name='Publicada')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Pauta Publicada em')),
                ('genareted_at', models.DateTimeField(auto_now=True, verbose_name='Data Gerada')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gradebooks', to='academics.academicyear', verbose_name='Ano Letivo')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gradebooks', to='academics.group', verbose_name='Turma')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gradebooks', to='academics.subject', verbose_name='Disciplina')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Nota')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Data de Lançamento')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Atualizado em')),
                ('observation', models.TextField(blank=True, verbose_name='Observação')),
                ('avaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='grades.evaluation', verbose_name='Avalição')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='enrollments.enrollment', verbose_name='Matricula')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('enrollment', 'avaluation'), name='unique_grade_avaluation')],
            },
        ),
    ]
