# Generated by Django 6.1 on 2026-09-17 08:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('accounts', '0001_initial'),
        ('enrollments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('AC', 'Avaliação Contínua'), ('NPP', 'Prova do Professor'), ('NPT', 'Prova Trimestral')], max_length=10, unique=True, verbose_name='Tipo')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Avaliação')),
                ('gradeWeight', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Peso da Nota (%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Tipo de Avaliação',
                'verbose_name_plural': 'Tipos de Avaliação',
            },
        ),
        migrations.CreateModel(
            name='AcademicEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trimester', models.PositiveSmallIntegerField(choices=[(1, '1º Trimestre'), (2, '2º Trimestre'), (3, '3º Trimestre')], verbose_name='Trimestre')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Data da Realização')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='academic_evaluations', to='academics.group', verbose_name='Turma')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='academic_evaluations', to='academics.subject', verbose_name='Disciplina')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='academic_evaluations', to='grades.evaluation', verbose_name='Tipo de Avaliação')),
            ],
            options={
                'verbose_name': 'Avaliação Académica',
                'verbose_name_plural': 'Avaliações Académicas',
                'ordering': ['trimester', 'subject'],
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='Nota')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Lançamento')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('observation', models.TextField(blank=True, verbose_name='Observação')),
                ('academic_evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='grades.academicevaluation', verbose_name='Avaliação')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='enrollments.enrollment', verbose_name='Matrícula')),
                ('launched_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='launched_grades', to='accounts.teacher', verbose_name='Lançada por')),
            ],
            options={
                'verbose_name': 'Nota',
                'verbose_name_plural': 'Notas',
            },
        ),
        migrations.CreateModel(
            name='GradeBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trimester', models.PositiveSmallIntegerField(choices=[(1, '1º Trimestre'), (2, '2º Trimestre'), (3, '3º Trimestre')], verbose_name='Trimestre')),
                ('posted', models.BooleanField(default=False, verbose_name='Publicada')),
                ('posted_at', models.DateTimeField(blank=True, null=True, verbose_name='Pauta Publicada em')),
                ('generated_at', models.DateTimeField(auto_now=True, verbose_name='Data Gerada')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gradebooks', to='academics.academicyear', verbose_name='Ano Letivo')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gradebooks', to='academics.group', verbose_name='Turma')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gradebooks', to='academics.subject', verbose_name='Disciplina')),
            ],
            options={
                'verbose_name': 'Pauta',
                'verbose_name_plural': 'Pautas',
            },
        ),
        migrations.AddConstraint(
            model_name='academicevaluation',
            constraint=models.UniqueConstraint(fields=('evaluation', 'subject', 'group', 'trimester'), name='unique_academic_evaluation'),
        ),
        migrations.AddConstraint(
            model_name='grade',
            constraint=models.UniqueConstraint(fields=('enrollment', 'academic_evaluation'), name='unique_grade_academic_evaluation'),
        ),
        migrations.AddConstraint(
            model_name='gradebook',
            constraint=models.UniqueConstraint(fields=('group', 'subject', 'academic_year', 'trimester'), name='unique_gradebook_group_subject_year_trimester'),
        ),
    ]
