# Generated by Django 6.1 on 2026-09-17 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=20, unique=True, verbose_name='Ano Letivo')),
                ('start_date', models.DateField(verbose_name='Data de Início')),
                ('end_date', models.DateField(verbose_name='Data de Fim')),
                ('is_active', models.BooleanField(default=False, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Ano Letivo',
                'verbose_name_plural': 'Anos Letivos',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nome')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Código do Curso')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('duration', models.PositiveSmallIntegerField(verbose_name='Duração do Curso (anos)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=50, verbose_name='Designação')),
                ('course_year', models.PositiveSmallIntegerField(verbose_name='Ano do Curso')),
                ('shift', models.CharField(choices=[('MANHA', 'Manhã'), ('TARDE', 'Tarde'), ('NOITE', 'Noite')], max_length=10, verbose_name='Turno')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='academics.academicyear', verbose_name='Ano Letivo')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='academics.course', verbose_name='Curso')),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
                'ordering': ['academic_year', 'course', 'designation'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nome')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Código da Disciplina')),
                ('course_year', models.PositiveSmallIntegerField(verbose_name='Ano do Curso')),
                ('workload', models.PositiveIntegerField(default=0, verbose_name='Carga Horária')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subjects', to='academics.course', verbose_name='Curso')),
            ],
            options={
                'verbose_name': 'Disciplina',
                'verbose_name_plural': 'Disciplinas',
                'ordering': ['course_year', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TeacherAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_assignment', models.DateField(auto_now_add=True, verbose_name='Data de Atribuição')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teacherassignments', to='academics.group', verbose_name='Turma')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teacherassignments', to='academics.subject', verbose_name='Disciplina')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teacherassignments', to='accounts.teacher', verbose_name='Professor')),
            ],
            options={
                'verbose_name': 'Atribuição de Professor',
                'verbose_name_plural': 'Atribuições de Professores',
            },
        ),
        migrations.AddConstraint(
            model_name='group',
            constraint=models.UniqueConstraint(fields=('course', 'academic_year', 'designation'), name='unique_group_per_course_year'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(fields=('course', 'name'), name='unique_subject_name_per_course'),
        ),
        migrations.AddConstraint(
            model_name='teacherassignment',
            constraint=models.UniqueConstraint(fields=('teacher', 'subject', 'group'), name='unique_assignment_teacher'),
        ),
    ]
