# Generated by Django 6.0.7 on 2026-08-16 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=20, unique=True, verbose_name='Ano Letivo')),
                ('start_date', models.DateField(verbose_name='Data de Inicio')),
                ('end_date', models.DateField(verbose_name='Data de fim')),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nome')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Codigo do Curso')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('duration', models.PositiveBigIntegerField(verbose_name='Duração do Curso')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=50, verbose_name='Designação')),
                ('course_year', models.PositiveIntegerField(verbose_name='Ano do curso')),
                ('shit', models.CharField(choices=[('MANHA', 'Manhã'), ('TARDE', 'Tarde'), ('NOITE', 'Noite')], max_length=10, verbose_name='Turno')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='academics.academicyear', verbose_name='Ano Letivo')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='academics.course', verbose_name='Curso')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nome')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Codigo da Disciplina')),
                ('course_year', models.PositiveIntegerField(verbose_name='Ano do Curso')),
                ('trimester', models.PositiveIntegerField(verbose_name='trimeste')),
                ('workload', models.PositiveIntegerField(default=0, verbose_name='Caraga Horária')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subjects', to='academics.course', verbose_name='Curso')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_assignment', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teacherassignments', to='academics.group', verbose_name='Turma')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teacherassignments', to='academics.subject', verbose_name='Dsiciplina')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teacherassignments', to='accounts.teacher', verbose_name='Professor')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('teacher', 'subject', 'group'), name='unique_assignment_teacher')],
            },
        ),
    ]
