# Generated by Django 6.0.7 on 2026-08-17 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicyear',
            options={'verbose_name': 'Ano Letivo'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Curso'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Turma'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'Disciplina'},
        ),
        migrations.AlterModelOptions(
            name='teacherassignment',
            options={'verbose_name': 'Atribuições a Professore'},
        ),
        migrations.AlterField(
            model_name='academicyear',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Ativo'),
        ),
    ]
