# Generated by Django 6.0.7 on 2026-08-18 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_alter_academicyear_options_alter_course_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherassignment',
            name='date_assignment',
            field=models.DateField(auto_now_add=True, verbose_name='Data Atribuição'),
        ),
    ]
