# Generated by Django 6.0.7 on 2026-08-21 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_alter_teacherassignment_date_assignment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacherassignment',
            options={'verbose_name': 'Atribuições a Professor', 'verbose_name_plural': 'Atribuições a Professores'},
        ),
    ]
