# Generated by Django 6.1 on 2026-09-17 20:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='father_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nome do Pai'),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, choices=[('MASCULINO', 'Masculino'), ('FEMININO', 'Feminino')], max_length=10, verbose_name='Género'),
        ),
        migrations.AddField(
            model_name='student',
            name='id_card_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Formato de Bilhete de Identidade inválido (ex: 003267618LA047).', regex='^\\d{9}[A-Z]{2}\\d{3}$')], verbose_name='Nº do Bilhete de Identidade'),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nome da Mãe'),
        ),
        migrations.AddField(
            model_name='student',
            name='place_of_birth',
            field=models.CharField(blank=True, max_length=100, verbose_name='Naturalidade'),
        ),
        migrations.AddField(
            model_name='student',
            name='province',
            field=models.CharField(blank=True, max_length=100, verbose_name='Província'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='birthdate',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='father_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nome do Pai'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='gender',
            field=models.CharField(blank=True, choices=[('MASCULINO', 'Masculino'), ('FEMININO', 'Feminino')], max_length=10, verbose_name='Género'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='id_card_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Formato de Bilhete de Identidade inválido (ex: 003267618LA047).', regex='^\\d{9}[A-Z]{2}\\d{3}$')], verbose_name='Nº do Bilhete de Identidade'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='mother_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nome da Mãe'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='place_of_birth',
            field=models.CharField(blank=True, max_length=100, verbose_name='Naturalidade'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='province',
            field=models.CharField(blank=True, max_length=100, verbose_name='Província'),
        ),
        migrations.AlterField(
            model_name='student',
            name='birthdate',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
    ]
