# Generated by Django 6.1 on 2026-09-17 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_student_father_name_student_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='address',
            field=models.CharField(default='Benfica, Mundial, Praça Nova', max_length=255, verbose_name='Morada'),
            preserve_default=False,
        ),
    ]
