# Generated by Django 6.0.7 on 2026-08-18 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_student_options_alter_teacher_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='employee_number',
        ),
    ]
